<a href="https://colab.research.google.com/github/Killeryoung/NM/blob/main/%D0%9B_%D0%A0_%E2%84%964_%D0%93%D1%83%D1%80%D0%BA%D0%BE_%D0%94%D0%B0%D0%BD%D0%B8%D0%BB%D0%BE_%D0%92%D0%B0%D1%80%D1%96%D0%B0%D0%BD%D1%82_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Був присутній на парі.

In [1]:
!pip install numpy

In [2]:
import numpy as np
np.__version__


'2.0.2'

In [3]:
matrix = np.random.randint(1, 6, size=(3, 3))

matrix

array([[1, 4, 1],
       [1, 3, 3],
       [2, 4, 2]])

In [23]:
np.linalg.det(matrix)

np.float64(7.999999999999998)

In [17]:
np.prod(matrix)

np.int64(576)

In [6]:
prod_1 = np.prod(matrix[0])
prod_2 = np.prod(matrix[1])
prod_3 = np.prod(matrix[2])
prod_1*prod_2*prod_3

np.int64(576)

In [18]:
np.sum(matrix)

np.int64(21)

In [19]:
np.max(matrix)

np.int64(4)

In [20]:
np.min(matrix)

np.int64(1)

In [21]:
np.mean(matrix)

np.float64(2.3333333333333335)

In [22]:
np.sqrt(matrix)

array([[1.        , 2.        , 1.        ],
       [1.        , 1.73205081, 1.73205081],
       [1.41421356, 2.        , 1.41421356]])

In [24]:
np.sum(matrix, axis=1).reshape(-1,1)

array([[6],
       [7],
       [8]])

In [28]:
vector=np.random.randint(0,10, size=25)
vector

array([9, 0, 6, 1, 6, 2, 9, 1, 6, 7, 5, 6, 0, 8, 9, 0, 9, 2, 9, 8, 6, 2,
       0, 5, 6])

In [32]:
sort_vector=np.sort(vector)[::-1]
sort_vector

array([9, 9, 9, 9, 9, 8, 8, 7, 6, 6, 6, 6, 6, 6, 5, 5, 2, 2, 2, 1, 1, 0,
       0, 0, 0])

In [35]:
a = np.array([[1, 2, -1], [3, 4, 1], [5, 1, -3]])
b = np.array([-3, 1, -2])

x = np.linalg.solve(a, b)
print('Вбудована функція', x1.round(1))

inv_a = np.linalg.inv(a)
x1 = inv_a.dot(b)
print('Матричний метод', x1.round(1))

Вбудована функція [ 1. -1.  2.]
Матричний метод [ 1. -1.  2.]


In [36]:
# Метод Крамера
def kramer(a, b):
    det_a = np.linalg.det(a)
    if det_a != 0:
        solutions = []
        for i in range(len(a)):
            modified_a = np.copy(a)
            modified_a[:, i] = b
            solutions.append(round(np.linalg.det(modified_a) / det_a, 1))

        print('Solving a system of linear algebraic equations by Cramer\'s method:')
        #print('x =', solutions)

    else:
        print('Determinant equals zero, the system has no solutions')
    return solutions
# Виклик функцій для розв'язання системи
print(kramer(a, b))

Solving a system of linear algebraic equations by Cramer's method:
[np.float64(1.0), np.float64(-1.0), np.float64(2.0)]
